version: '3'

services:
    golang:
        build: ./docker/golang
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        volumes:
            - .:/todo-app-api
        tty: true

    mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        container_name: mysql-container-5.7
        ports:
            - "3306:3306"